---
abstract: 'Underscore.js port to Perl'
author:
  - 'Viacheslav Tykhanovskyi <vti@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.62
  Test::Spec: 0
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Underscore
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  B: 0
  List::MoreUtils: 0
  List::Util: 0
  perl: 5.8.7
resources:
  bugtracker: http://github.com/vti/underscore-perl/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/vti/underscore-perl/
version: 0.01
